name: "${{ github.event.inputs.deploy_message }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production
      deploy_message:
        description: 'Enter a custom message'
        required: true
        default: 'Deployment to dev'
        type: string
jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Message: ${{ github.event.inputs.deploy_message }}"
