name: Application Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production
      deploy_message:
        description: 'Enter a custom message'
        required: true
        default: 'Deployment to dev'
        type: string
      clear_cache:
        description: 'Purge cache'
        required: true
        default: false
        type: boolean
jobs:
  run-manual:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Show inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Message: ${{ github.event.inputs.deploy_message }}"
      - name: ${{ github.event.inputs.deploy_message }}
        run: |
          echo "This is the ${{ vars.IDENT_STRING }}"
          if [[ "${{ github.event.inputs.enable_debug }}" == "true" ]]; then
            echo "Purging Cache"
          else
            echo "Proceeding without purging Cache"
          fi
